### ISSUE TITLE
Survivor options not showing up

### ISSUE THREAD

**Issue by Fumeknight79** [KingEnderBrine/-RoR2-PartialItemDisplay#2]
I recently downloaded this mod to get around the issue of some items not displaying well on custom survivors or custom skins. To this end, the mod works well, except for the fact that the default option is the only config available for change. The lobby settings only shows the default section, and config editor in the mod launcher only shows Main (which only allows for disabling the entire mod) and Default.

Overall, this is only a minor inconvenience, since the mod does work for the most part, but there are some items I would like to disable for only a few survivors (the goat hoof looks fine on a commander skin, but horrible on other custom skins, for instance).

Also, this is my first time posting an issue, so please forgive me if I did something wrong or if I forgot something.

**Comment by KingEnderBrine** [comment]
Thanks for the report. I will take a look on the week end

**Comment by KingEnderBrine** [comment]
Published an update.
